stages:
  - build
compile_pdf:
  image: aergus/latex
  script:
    - latexmk -pdf thesis.tex
    - pdfinfo thesis.pdf
    - latexmk -pdf presentation.tex
    - pdfinfo presentation.pdf
    - latexmk -pdf summary.tex
    - pdfinfo summary.pdf
  stage: build
  artifacts:
    paths:
      - "thesis.pdf"
      - presentation.pdf
      - summary.pdf
